In [1]:
#Import dependencies
import pandas as pd
import os

In [2]:
#Access file as df
filepath = os.path.join("..",'Validated_Data', 'nba_draft_combine_all_years_val.csv')

combine = pd.read_csv(filepath)

combine["player"] = combine["player"].str.replace(".", " ")
combine

,unnamed:_0,player,year,draft_pick,height_no_shoes,height_with_shoes,wingspan,standing_reach,vertical_max,vertical_max_reach,vertical_no_step,vertical_no_step_reach,weight,body_fat,hand_length,hand_width,bench,agility,sprint
0,0,Blake Griffin,2009,1.0,80.50,82.00,83.25,105.0,35.5,140.5,32.0,137.0,248.0,8.2,NaN,NaN,22.0,10.95,3.28
1,1,Terrence Williams,2009,11.0,77.00,78.25,81.00,103.5,37.0,140.5,30.5,134.0,213.0,5.1,NaN,NaN,9.0,11.15,3.18
2,2,Gerald Henderson,2009,12.0,76.00,77.00,82.25,102.5,35.0,137.5,31.5,134.0,215.0,4.4,NaN,NaN,8.0,11.17,3.14
3,3,Tyler Hansbrough,2009,13.0,80.25,81.50,83.50,106.0,34.0,140.0,27.5,133.5,234.0,8.5,NaN,NaN,18.0,11.12,3.27
4,4,Earl Clark,2009,14.0,80.50,82.25,86.50,109.5,33.0,142.5,28.5,138.0,228.0,5.2,NaN,NaN,5.0,11.17,3.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
512,512,Peter Jok,2017,NaN,76.25,77.75,80.00,102.0,31.0,133.0,26.5,128.5,202.0,11.0,8.25,9.50,NaN,11.34,3.41
513,513,Rawle Alkins,2017,NaN,74.50,75.75,80.75,99.0,40.5,139.5,31.5,130.5,223.0,11.0,8.75,10.00,NaN,11.99,3.30
514,514,Sviatoslav Mykhailiuk,2017,NaN,78.50,79.50,77.00,100.0,33.0,133.0,27.0,127.0,220.0,11.4,8.00,9.25,NaN,12.40,3.53
515,515,Thomas Welsh,2017,NaN,83.50,84.50,84.00,109.5,NaN,NaN,NaN,NaN,254.0,10.9,9.00,10.50,NaN,NaN,NaN
516,516,V J Beachem,2017,NaN,78.25,80.00,82.25,104.5,37.0,141.5,30.0,134.5,193.0,6.8,8.50,9.00,NaN,11.18,3.26

In [3]:
#Access players csv for player ID
file = os.path.join("..",'Validated_Data', 'players_val.csv')

players = pd.read_csv(file)

#Replace all "." for more consistent data
players["player_name"] = players["player_name"].str.replace(".", " ")
players

           player_name     team_id  player_id  season
0        Royce O'Neale  1610612762    1626220    2019
1     Bojan Bogdanovic  1610612762     202711    2019
2          Rudy Gobert  1610612762     203497    2019
3     Donovan Mitchell  1610612762    1628378    2019
4          Mike Conley  1610612762     201144    2019
...                ...         ...        ...     ...
7223       Lanny Smith  1610612758     201831    2009
7224     Warren Carter  1610612752     201999    2009
7225      Bennet Davis  1610612751     201834    2009
7226    Brian Hamilton  1610612751     201646    2009
7227   Wesley Matthews  1610612762     500032    2009

[7228 rows x 4 columns]

In [4]:
#Clean the players df for just the year 2018
players = players.loc[players['season'] == 2018]

In [5]:
#Merge the combine data and players to get Player ID as primary key 
merged = pd.merge(combine, players, left_on="player", right_on="player_name")

In [6]:
list(merged)

['unnamed:_0',
 'player',
 'year',
 'draft_pick',
 'height_no_shoes',
 'height_with_shoes',
 'wingspan',
 'standing_reach',
 'vertical_max',
 'vertical_max_reach',
 'vertical_no_step',
 'vertical_no_step_reach',
 'weight',
 'body_fat',
 'hand_length',
 'hand_width',
 'bench',
 'agility',
 'sprint',
 'player_name',
 'team_id',
 'player_id',
 'season']

In [7]:
#reorder DF
clean_df = merged[['player_id','player','year','team_id',
 'draft_pick',
 'height_no_shoes',
 'height_with_shoes',
 'wingspan',
 'standing_reach',
 'vertical_max',
 'vertical_max_reach',
 'vertical_no_step',
 'vertical_no_step_reach',
 'weight',
 'body_fat',
 'hand_length',
 'hand_width',
 'bench',
 'agility',
 'sprint',
 'season']]

In [8]:
clean_df.drop_duplicates(subset="player_id", keep='first')

,player_id,player,year,team_id,draft_pick,height_no_shoes,height_with_shoes,wingspan,standing_reach,vertical_max,...,vertical_no_step,vertical_no_step_reach,weight,body_fat,hand_length,hand_width,bench,agility,sprint,season
0,201933,Blake Griffin,2009,1610612765,1.0,80.50,82.00,83.25,105.0,35.5,...,32.0,137.0,248.0,8.2,NaN,NaN,22.0,10.95,3.28,2018
1,201949,James Johnson,2009,1610612748,16.0,79.00,79.75,84.75,105.5,35.0,...,30.5,136.0,257.0,12.0,NaN,NaN,18.0,11.21,3.23,2018
2,201950,Jrue Holiday,2009,1610612740,17.0,75.25,76.25,79.00,100.5,34.0,...,28.5,129.0,199.0,6.3,NaN,NaN,6.0,10.64,3.21,2018
3,201952,Jeff Teague,2009,1610612750,19.0,72.25,73.50,79.50,98.5,36.5,...,30.5,129.0,175.0,4.5,NaN,NaN,13.0,11.05,3.18,2018
4,201954,Darren Collison,2009,1610612754,21.0,72.25,73.50,75.00,96.5,33.5,...,30.5,127.0,166.0,5.7,NaN,NaN,9.0,10.45,3.10,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1628405,Johnathan Motley,2017,1610612746,NaN,79.75,80.75,88.00,108.0,NaN,...,NaN,NaN,238.0,NaN,9.00,9.50,NaN,NaN,NaN,2018
305,1628424,Kobi Simmons,2017,1610612739,NaN,75.25,76.50,78.00,99.0,38.5,...,30.5,129.5,166.0,5.0,8.50,9.50,NaN,11.15,3.18,2018
306,1629021,Moritz Wagner,2017,1610612747,NaN,82.00,83.25,84.00,108.0,32.5,...,25.5,133.5,231.0,6.7,8.75,10.75,NaN,12.00,3.35,2018
307,1628959,Rawle Alkins,2017,1610612741,NaN,74.50,75.75,80.75,99.0,40.5,...,31.5,130.5,223.0,11.0,8.75,10.00,NaN,11.99,3.30,2018
308,1629118,Thomas Welsh,2017,1610612743,NaN,83.50,84.50,84.00,109.5,NaN,...,NaN,NaN,254.0,10.9,9.00,10.50,NaN,NaN,NaN,2018

In [15]:
clean_df.rename(columns={
    'player': 'player_name'
})

,player_id,player_name,year,team_id,draft_pick,height_no_shoes,height_with_shoes,wingspan,standing_reach,vertical_max,...,vertical_no_step,vertical_no_step_reach,weight,body_fat,hand_length,hand_width,bench,agility,sprint,season
0,201933,Blake Griffin,2009,1610612765,1.0,80.50,82.00,83.25,105.0,35.5,...,32.0,137.0,248.0,8.2,NaN,NaN,22.0,10.95,3.28,2018
1,201949,James Johnson,2009,1610612748,16.0,79.00,79.75,84.75,105.5,35.0,...,30.5,136.0,257.0,12.0,NaN,NaN,18.0,11.21,3.23,2018
2,201950,Jrue Holiday,2009,1610612740,17.0,75.25,76.25,79.00,100.5,34.0,...,28.5,129.0,199.0,6.3,NaN,NaN,6.0,10.64,3.21,2018
3,201952,Jeff Teague,2009,1610612750,19.0,72.25,73.50,79.50,98.5,36.5,...,30.5,129.0,175.0,4.5,NaN,NaN,13.0,11.05,3.18,2018
4,201954,Darren Collison,2009,1610612754,21.0,72.25,73.50,75.00,96.5,33.5,...,30.5,127.0,166.0,5.7,NaN,NaN,9.0,10.45,3.10,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,1628405,Johnathan Motley,2017,1610612746,NaN,79.75,80.75,88.00,108.0,NaN,...,NaN,NaN,238.0,NaN,9.00,9.50,NaN,NaN,NaN,2018
305,1628424,Kobi Simmons,2017,1610612739,NaN,75.25,76.50,78.00,99.0,38.5,...,30.5,129.5,166.0,5.0,8.50,9.50,NaN,11.15,3.18,2018
306,1629021,Moritz Wagner,2017,1610612747,NaN,82.00,83.25,84.00,108.0,32.5,...,25.5,133.5,231.0,6.7,8.75,10.75,NaN,12.00,3.35,2018
307,1628959,Rawle Alkins,2017,1610612741,NaN,74.50,75.75,80.75,99.0,40.5,...,31.5,130.5,223.0,11.0,8.75,10.00,NaN,11.99,3.30,2018
308,1629118,Thomas Welsh,2017,1610612743,NaN,83.50,84.50,84.00,109.5,NaN,...,NaN,NaN,254.0,10.9,9.00,10.50,NaN,NaN,NaN,2018

In [16]:
clean_df.to_csv('../outputs/combine_cleaned.csv', index = False)

In [17]:
clean_df.dtypes

player_id                   int64
player                     object
year                        int64
team_id                     int64
draft_pick                float64
height_no_shoes           float64
height_with_shoes         float64
wingspan                  float64
standing_reach            float64
vertical_max              float64
vertical_max_reach        float64
vertical_no_step          float64
vertical_no_step_reach    float64
weight                    float64
body_fat                  float64
hand_length               float64
hand_width                float64
bench                     float64
agility                   float64
sprint                    float64
season                      int64
dtype: object