In [1]:
import pandas as pd
import os

In [2]:
teams_filepath = os.path.join('..', 'Validated_Data', 'player_stats_val.csv')

data = pd.read_csv(teams_filepath)

data.head()

,rk,player,pos,age,tm,g,gs,mp,fg,fga,...,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,1,Álex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,0.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,0.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [3]:
# reading csv file from url  

# dropping null value columns to avoid errors 
data.dropna(inplace = True) 
  
# new data frame with split value columns 
new = data["player"].str.split("\\", n = 1, expand = True)  
  
# making separate first name column from new data frame 
data["name"]= new[0] 
  
# df display 
data

,rk,player,pos,age,tm,g,gs,mp,fg,fga,...,orb,drb,trb,ast,stl,blk,tov,pf,pts,name
0,1,Álex Abrines\abrinal01,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3,Álex Abrines
1,2,Quincy Acy\acyqu01,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy
2,3,Jaylen Adams\adamsja01,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams
3,4,Steven Adams\adamsst01,C,25,OKC,80,80,33.4,6.0,10.1,...,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams
4,5,Bam Adebayo\adebaba01,C,21,MIA,82,28,23.3,3.4,5.9,...,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,523,Guerschon Yabusele\yabusgu01,PF,23,BOS,41,1,6.1,0.9,1.9,...,0.6,0.7,1.3,0.4,0.2,0.2,0.4,0.8,2.3,Guerschon Yabusele
698,525,Thaddeus Young\youngth01,PF,30,IND,81,81,30.7,5.5,10.4,...,2.4,4.1,6.5,2.5,1.5,0.4,1.5,2.4,12.6,Thaddeus Young
699,526,Trae Young\youngtr01,PG,20,ATL,81,81,30.9,6.5,15.5,...,0.8,2.9,3.7,8.1,0.9,0.2,3.8,1.7,19.1,Trae Young
700,527,Cody Zeller\zelleco01,C,26,CHO,49,47,25.4,3.9,7.0,...,2.2,4.6,6.8,2.1,0.8,0.8,1.3,3.3,10.1,Cody Zeller
701,528,Tyler Zeller\zellety01,C,29,TOT,6,1,15.5,2.7,5.0,...,1.8,2.2,4.0,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller

In [4]:
#rearrange columns
clean_stats = data[['name',
'rk',
 'pos',
 'age',
 'tm',
 'g',
 'gs',
 'mp',
 'fg',
 'fga',
 'fg%',
 '3p',
 '3pa',
 '3p%',
 '2p',
 '2pa',
 '2p%',
 'efg%',
 'ft',
 'fta',
 'ft%',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts']]

In [5]:
#drop duplicates due to merge
clean_stats = clean_stats.drop_duplicates(subset=['name'], keep='first')
clean_stats['name'] = clean_stats['name'].str.replace('.','')
clean_stats

,name,rk,pos,age,tm,g,gs,mp,fg,fga,...,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts
0,Álex Abrines,1,SG,25,OKC,31,2,19.0,1.8,5.1,...,0.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,Quincy Acy,2,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,Jaylen Adams,3,PG,22,ATL,34,1,12.6,1.1,3.2,...,0.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,Steven Adams,4,C,25,OKC,80,80,33.4,6.0,10.1,...,0.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,Bam Adebayo,5,C,21,MIA,82,28,23.3,3.4,5.9,...,0.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,Guerschon Yabusele,523,PF,23,BOS,41,1,6.1,0.9,1.9,...,0.682,0.6,0.7,1.3,0.4,0.2,0.2,0.4,0.8,2.3
698,Thaddeus Young,525,PF,30,IND,81,81,30.7,5.5,10.4,...,0.644,2.4,4.1,6.5,2.5,1.5,0.4,1.5,2.4,12.6
699,Trae Young,526,PG,20,ATL,81,81,30.9,6.5,15.5,...,0.829,0.8,2.9,3.7,8.1,0.9,0.2,3.8,1.7,19.1
700,Cody Zeller,527,C,26,CHO,49,47,25.4,3.9,7.0,...,0.787,2.2,4.6,6.8,2.1,0.8,0.8,1.3,3.3,10.1
701,Tyler Zeller,528,C,29,TOT,6,1,15.5,2.7,5.0,...,0.778,1.8,2.2,4.0,0.7,0.2,0.5,0.7,3.3,7.7

In [6]:
#filepath and df to players
file = os.path.join("..",'Validated_Data', 'players_val.csv')

players = pd.read_csv(file)
players

           player_name     team_id  player_id  season
0        Royce O'Neale  1610612762    1626220    2019
1     Bojan Bogdanovic  1610612762     202711    2019
2          Rudy Gobert  1610612762     203497    2019
3     Donovan Mitchell  1610612762    1628378    2019
4          Mike Conley  1610612762     201144    2019
...                ...         ...        ...     ...
7223       Lanny Smith  1610612758     201831    2009
7224     Warren Carter  1610612752     201999    2009
7225      Bennet Davis  1610612751     201834    2009
7226    Brian Hamilton  1610612751     201646    2009
7227   Wesley Matthews  1610612762     500032    2009

[7228 rows x 4 columns]

In [7]:
#reduce players for season and edit their names for consistency
players = players.loc[players['season'] == 2018]

players["player_name"] = players["player_name"].str.replace('.', '')

<ipython-input-7-962ba5f61783>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players["player_name"] = players["player_name"].str.replace('.', '')

In [8]:
#merge the data
merged = pd.merge(clean_stats, players, left_on="name", right_on="player_name")

In [9]:
merged

,name,rk,pos,age,tm,g,gs,mp,fg,fga,...,ast,stl,blk,tov,pf,pts,player_name,team_id,player_id,season
0,Quincy Acy,2,PF,28,PHO,10,0,12.3,0.4,1.8,...,0.8,0.1,0.4,0.4,2.4,1.7,Quincy Acy,1610612756,203112,2018
1,Jaylen Adams,3,PG,22,ATL,34,1,12.6,1.1,3.2,...,1.9,0.4,0.1,0.8,1.3,3.2,Jaylen Adams,1610612737,1629121,2018
2,Steven Adams,4,C,25,OKC,80,80,33.4,6.0,10.1,...,1.6,1.5,1.0,1.7,2.6,13.9,Steven Adams,1610612760,203500,2018
3,Bam Adebayo,5,C,21,MIA,82,28,23.3,3.4,5.9,...,2.2,0.9,0.8,1.5,2.5,8.9,Bam Adebayo,1610612748,1628389,2018
4,Deng Adel,6,SF,21,CLE,19,3,10.2,0.6,1.9,...,0.3,0.1,0.2,0.3,0.7,1.7,Deng Adel,1610612739,1629061,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
527,Trae Young,526,PG,20,ATL,81,81,30.9,6.5,15.5,...,8.1,0.9,0.2,3.8,1.7,19.1,Trae Young,1610612737,1629027,2018
528,Cody Zeller,527,C,26,CHO,49,47,25.4,3.9,7.0,...,2.1,0.8,0.8,1.3,3.3,10.1,Cody Zeller,1610612766,203469,2018
529,Tyler Zeller,528,C,29,TOT,6,1,15.5,2.7,5.0,...,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,1610612763,203092,2018
530,Tyler Zeller,528,C,29,TOT,6,1,15.5,2.7,5.0,...,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,1610612737,203092,2018
531,Tyler Zeller,528,C,29,TOT,6,1,15.5,2.7,5.0,...,0.7,0.2,0.5,0.7,3.3,7.7,Tyler Zeller,1610612749,203092,2018

In [10]:
cleaned_df = merged.drop_duplicates(subset=['name'], keep='first')

In [11]:
list(cleaned_df)

['name',
 'rk',
 'pos',
 'age',
 'tm',
 'g',
 'gs',
 'mp',
 'fg',
 'fga',
 'fg%',
 '3p',
 '3pa',
 '3p%',
 '2p',
 '2pa',
 '2p%',
 'efg%',
 'ft',
 'fta',
 'ft%',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'pts',
 'player_name',
 'team_id',
 'player_id',
 'season']

In [12]:
stats = cleaned_df[['player_id',
 'team_id', 'name',
 'pos',
 'age',
 'tm',
 'g',
 'gs',
 'mp',
 'fg',
 'fga',
 'fg%',
 '3p',
 '3pa',
 '3p%',
 '2p',
 '2pa',
 '2p%',
 'efg%',
 'ft',
 'fta',
 'ft%',
'pts',
 'orb',
 'drb',
 'trb',
 'ast',
 'stl',
 'blk',
 'tov',
 'pf',
 'season']]

In [13]:
#rename columns
stats = stats.rename(columns={
    "name": "player_name",
    "fg%":"fg_percent",
    "3p":"ThreeP_m",
    "3pa":"ThreeP_a",
    "3p%":"ThreeP_percent",
    "2pa":"TwoP_a",
    "2p":"TwoP_m",
    "2p%":"TwoP_percent",
    "efg%":"efg_percent",
    "ft%":"ft_percent"
})

In [14]:
stats

,player_id,team_id,player_name,pos,age,tm,g,gs,mp,fg,...,pts,orb,drb,trb,ast,stl,blk,tov,pf,season
0,203112,1610612756,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,...,1.7,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,2018
1,1629121,1610612737,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,...,3.2,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,2018
2,203500,1610612760,Steven Adams,C,25,OKC,80,80,33.4,6.0,...,13.9,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,2018
3,1628389,1610612748,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,...,8.9,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,2018
4,1629061,1610612739,Deng Adel,SF,21,CLE,19,3,10.2,0.6,...,1.7,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525,1627824,1610612738,Guerschon Yabusele,PF,23,BOS,41,1,6.1,0.9,...,2.3,0.6,0.7,1.3,0.4,0.2,0.2,0.4,0.8,2018
526,201152,1610612754,Thaddeus Young,PF,30,IND,81,81,30.7,5.5,...,12.6,2.4,4.1,6.5,2.5,1.5,0.4,1.5,2.4,2018
527,1629027,1610612737,Trae Young,PG,20,ATL,81,81,30.9,6.5,...,19.1,0.8,2.9,3.7,8.1,0.9,0.2,3.8,1.7,2018
528,203469,1610612766,Cody Zeller,C,26,CHO,49,47,25.4,3.9,...,10.1,2.2,4.6,6.8,2.1,0.8,0.8,1.3,3.3,2018
529,203092,1610612763,Tyler Zeller,C,29,TOT,6,1,15.5,2.7,...,7.7,1.8,2.2,4.0,0.7,0.2,0.5,0.7,3.3,2018

In [15]:
stats.columns

Index(['player_id', 'team_id', 'player_name', 'pos', 'age', 'tm', 'g', 'gs',
       'mp', 'fg', 'fga', 'fg_percent', 'ThreeP_m', 'ThreeP_a',
       'ThreeP_percent', 'TwoP_m', 'TwoP_a', 'TwoP_percent', 'efg_percent',
       'ft', 'fta', 'ft_percent', 'pts', 'orb', 'drb', 'trb', 'ast', 'stl',
       'blk', 'tov', 'pf', 'season'],
      dtype='object')

In [16]:
stats.to_csv('../outputs/g_stats_cleaned.csv', index = True)